/* eslint-disable @next/next/no-img-element */
import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio - Prem Kumar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/tabicon.ico" />
      </Head>
      <nav>
        <img src="/logo.svg" alt="logo" />
        About Projects Contact
      </nav>
      <main className={styles.main}>
        <section>
          About: Hello 👋 I&apos;m Prem Kumar Passionate in React technology
          React
        </section>
        <section>Projects: Rock scissor game Wordle TODO App</section>
      </main>

      <footer className={styles.footer}>LinkedIn Facebook Twitter</footer>
    </div>
  )
}
